Buildroot: /home/wbooth/git/rpm/clearscene-opendias-0.8.1
Name: clearscene-opendias
Version: 0.8.1
Release: 2
Summary: Document Imaging Archive System (openDIAS).
License: see /usr/share/doc/clearscene-opendias/copyright
Distribution: Debian
Group: Converted/clearscene

%define _rpmdir ../
%define _rpmfilename %%{NAME}-%%{VERSION}-%%{RELEASE}.%%{ARCH}.rpm
%define _unpackaged_files_terminate_build 0

%description
Home document imaging, with OCR. Scan documents (with SANE) or import ODF documents, assign tags. Use openDIAS to store all our letters, bills, statements, etc in a convenient, safe and easily retrievable way.


(Converted from a deb package by alien version 8.86.)

%files
%dir "/"
%dir "/usr/"
%dir "/usr/share/"
%dir "/usr/share/doc/"
%dir "/usr/share/doc/clearscene-opendias/"
"/usr/share/doc/clearscene-opendias/changelog.gz"
"/usr/share/doc/clearscene-opendias/copyright"
%dir "/usr/local/"
%dir "/usr/local/bin/"
"/usr/local/bin/opendiasconfig"
"/usr/local/bin/opendias"
%dir "/usr/local/share/"
%dir "/usr/local/share/opendias/"
"/usr/local/share/opendias/openDIAS.sqlite3.dmp.v6.sql"
"/usr/local/share/opendias/openDIAS.sqlite3.dmp.v3.sql"
%dir "/usr/local/share/opendias/webcontent/"
"/usr/local/share/opendias/webcontent/docDetail.html"
"/usr/local/share/opendias/webcontent/body.html"
"/usr/local/share/opendias/webcontent/docDetail.html.de"
"/usr/local/share/opendias/webcontent/accessControls.html.en"
"/usr/local/share/opendias/webcontent/body.html.en"
"/usr/local/share/opendias/webcontent/docList.html"
"/usr/local/share/opendias/webcontent/buglist.html.en"
"/usr/local/share/opendias/webcontent/acquire.html.de"
"/usr/local/share/opendias/webcontent/acquire.html"
"/usr/local/share/opendias/webcontent/acquire.html.en"
%dir "/usr/local/share/opendias/webcontent/images/"
"/usr/local/share/opendias/webcontent/images/spindown-closed.png"
"/usr/local/share/opendias/webcontent/images/opendias.jpg"
%dir "/usr/local/share/opendias/webcontent/images/easySlider/"
"/usr/local/share/opendias/webcontent/images/easySlider/btn_next.png"
"/usr/local/share/opendias/webcontent/images/easySlider/btn_prev.png"
"/usr/local/share/opendias/webcontent/images/openDIAS_sml.png"
"/usr/local/share/opendias/webcontent/images/openDIAS.png"
%dir "/usr/local/share/opendias/webcontent/images/datepicker/"
"/usr/local/share/opendias/webcontent/images/datepicker/datepicker_br.png"
"/usr/local/share/opendias/webcontent/images/datepicker/datepicker_l.png"
"/usr/local/share/opendias/webcontent/images/datepicker/datepicker_tl.png"
"/usr/local/share/opendias/webcontent/images/datepicker/field.png"
"/usr/local/share/opendias/webcontent/images/datepicker/datepicker_r.png"
"/usr/local/share/opendias/webcontent/images/datepicker/datepicker_b.png"
"/usr/local/share/opendias/webcontent/images/datepicker/datepicker_bl.png"
"/usr/local/share/opendias/webcontent/images/datepicker/datepicker_tr.png"
"/usr/local/share/opendias/webcontent/images/datepicker/datepicker_t.png"
%dir "/usr/local/share/opendias/webcontent/images/jquery-ui/"
"/usr/local/share/opendias/webcontent/images/jquery-ui/ui-bg_glass_80_d7ebf9_1x400.png"
"/usr/local/share/opendias/webcontent/images/jquery-ui/ui-icons_2e83ff_256x240.png"
"/usr/local/share/opendias/webcontent/images/jquery-ui/ui-icons_2694e8_256x240.png"
"/usr/local/share/opendias/webcontent/images/jquery-ui/ui-bg_flat_15_cd0a0a_40x100.png"
"/usr/local/share/opendias/webcontent/images/jquery-ui/ui-icons_ffffff_256x240.png"
"/usr/local/share/opendias/webcontent/images/jquery-ui/ui-bg_glass_50_3baae3_1x400.png"
"/usr/local/share/opendias/webcontent/images/jquery-ui/ui-icons_3d80b3_256x240.png"
"/usr/local/share/opendias/webcontent/images/jquery-ui/ui-bg_highlight-hard_70_000000_1x100.png"
"/usr/local/share/opendias/webcontent/images/jquery-ui/ui-icons_72a7cf_256x240.png"
"/usr/local/share/opendias/webcontent/images/jquery-ui/ui-bg_diagonals-thick_90_eeeeee_40x40.png"
"/usr/local/share/opendias/webcontent/images/jquery-ui/ui-bg_highlight-hard_100_f2f5f7_1x100.png"
"/usr/local/share/opendias/webcontent/images/jquery-ui/ui-bg_highlight-soft_25_ffef8f_1x100.png"
"/usr/local/share/opendias/webcontent/images/jquery-ui/pbar-ani.png"
"/usr/local/share/opendias/webcontent/images/jquery-ui/ui-bg_highlight-soft_100_deedf7_1x100.png"
"/usr/local/share/opendias/webcontent/images/jquery-ui/ui-bg_glass_100_e4f1fb_1x400.png"
"/usr/local/share/opendias/webcontent/images/openDIAS_64x64.ico"
"/usr/local/share/opendias/webcontent/images/texture.png"
"/usr/local/share/opendias/webcontent/images/spindown-open.png"
"/usr/local/share/opendias/webcontent/images/cabinet.jpg"
%dir "/usr/local/share/opendias/webcontent/images/tablesorter/"
"/usr/local/share/opendias/webcontent/images/tablesorter/prev.png"
"/usr/local/share/opendias/webcontent/images/tablesorter/last.png"
"/usr/local/share/opendias/webcontent/images/tablesorter/asc.png"
"/usr/local/share/opendias/webcontent/images/tablesorter/next.png"
"/usr/local/share/opendias/webcontent/images/tablesorter/first.png"
"/usr/local/share/opendias/webcontent/images/tablesorter/bg.png"
"/usr/local/share/opendias/webcontent/images/tablesorter/desc.png"
"/usr/local/share/opendias/webcontent/images/actionrequired.png"
"/usr/local/share/opendias/webcontent/accessControls.html"
"/usr/local/share/opendias/webcontent/accessControls.html.de"
%dir "/usr/local/share/opendias/webcontent/includes/"
"/usr/local/share/opendias/webcontent/includes/openDias.saveDetails.js"
"/usr/local/share/opendias/webcontent/includes/jquery.tablesorter.pager.js"
"/usr/local/share/opendias/webcontent/includes/openDias.getAccessDetails.js"
"/usr/local/share/opendias/webcontent/includes/jquery.easySlider.js"
"/usr/local/share/opendias/webcontent/includes/jquery.tablesorter.min.js"
"/usr/local/share/opendias/webcontent/includes/jquery.js"
"/usr/local/share/opendias/webcontent/includes/jquery.tagsinput.js"
"/usr/local/share/opendias/webcontent/includes/header.txt.en"
"/usr/local/share/opendias/webcontent/includes/sprintf-0.7-beta1.js"
"/usr/local/share/opendias/webcontent/includes/openDias.docList.js"
"/usr/local/share/opendias/webcontent/includes/openDias.loadDetails.js"
"/usr/local/share/opendias/webcontent/includes/jquery.canvas-loader.js"
"/usr/local/share/opendias/webcontent/includes/header.txt"
"/usr/local/share/opendias/webcontent/includes/openDias.filter.js"
%dir "/usr/local/share/opendias/webcontent/includes/local/"
"/usr/local/share/opendias/webcontent/includes/local/openDias.filter.js.resource.de"
"/usr/local/share/opendias/webcontent/includes/local/openDias.filter.js.resource.en"
"/usr/local/share/opendias/webcontent/includes/local/openDias.saveDetails.js.resource.de"
"/usr/local/share/opendias/webcontent/includes/local/openDias.loadDetails.js.resource.de"
"/usr/local/share/opendias/webcontent/includes/local/openDias.docList.js.resource.de"
"/usr/local/share/opendias/webcontent/includes/local/openDias.docList.js.resource.en"
"/usr/local/share/opendias/webcontent/includes/local/openDias.getAccessDetails.js.resource.en"
"/usr/local/share/opendias/webcontent/includes/local/openDias.loadDetails.js.resource.en"
"/usr/local/share/opendias/webcontent/includes/local/generic.resource.de"
"/usr/local/share/opendias/webcontent/includes/local/openDias.saveDetails.js.resource.en"
"/usr/local/share/opendias/webcontent/includes/local/generic.resource.en"
"/usr/local/share/opendias/webcontent/includes/local/openDias.acquire.js.resource.en"
"/usr/local/share/opendias/webcontent/includes/local/openDias.acquire.js.resource.de"
"/usr/local/share/opendias/webcontent/includes/local/openDias.getAccessDetails.js.resource.de"
"/usr/local/share/opendias/webcontent/includes/footer.txt"
"/usr/local/share/opendias/webcontent/includes/openDias.language.js"
"/usr/local/share/opendias/webcontent/includes/header.txt.de"
"/usr/local/share/opendias/webcontent/includes/jquery.gzoom.js"
"/usr/local/share/opendias/webcontent/includes/openDias.acquire.js"
"/usr/local/share/opendias/webcontent/includes/openDias.tablesorter.pager.addRemove.js"
"/usr/local/share/opendias/webcontent/includes/jquery-ui.min.js"
"/usr/local/share/opendias/webcontent/includes/jquery.mousewheel.js"
"/usr/local/share/opendias/webcontent/includes/footer.txt.de"
"/usr/local/share/opendias/webcontent/includes/footer.txt.en"
"/usr/local/share/opendias/webcontent/body.html.de"
"/usr/local/share/opendias/webcontent/docList.html.en"
"/usr/local/share/opendias/webcontent/docDetail.html.en"
%dir "/usr/local/share/opendias/webcontent/style/"
"/usr/local/share/opendias/webcontent/style/tablesorter.css"
"/usr/local/share/opendias/webcontent/style/jquery.gzoom.css"
"/usr/local/share/opendias/webcontent/style/datepicker.css"
"/usr/local/share/opendias/webcontent/style/jquery-ui.css"
"/usr/local/share/opendias/webcontent/style/jquery.easyslider.css"
"/usr/local/share/opendias/webcontent/style/jquery.tagsinput.css"
"/usr/local/share/opendias/webcontent/style/common.css"
"/usr/local/share/opendias/webcontent/docList.html.de"
"/usr/local/share/opendias/openDIAS.sqlite3.dmp.v5.sql"
"/usr/local/share/opendias/openDIAS.sqlite3.dmp.v1.sql"
"/usr/local/share/opendias/openDIAS.sqlite3.dmp.v2.sql"
"/usr/local/share/opendias/openDIAS.sqlite3.dmp.v4.sql"
%dir "/etc/"
%dir "/etc/init.d/"
%config "/etc/init.d/clearscene-opendias.sh"
%dir "/etc/opendias/"
%config "/etc/opendias/opendias.conf"
%dir "/var/"
%dir "/var/log/"
%dir "/var/log/opendias/"
%dir "/var/lib/"
%dir "/var/lib/opendias/"
