Buildroot: ./opendias
Name: opendias
Version: 0.9.5
Release: 1
Requires: libc.so.6 libsqlite3.so.0 libmicrohttpd.so.10 libcrypt.so.10 libssl.so.10 libuuid.so.1 sane-backends sane-backends-drivers-scanners iblept.so.3 file libtesseract.so.3 libxml2.so.2 libzzip-0.so.13 libpoppler-cpp.so.0
Summary: Document Imaging Archive System (openDIAS).
License: see /usr/doc/opendias/copyright
Distribution: Debian
Group: Converted/clearscene

%define _rpmdir ../
%define _rpmfilename %%{NAME}-%%{VERSION}-%%{RELEASE}.%%{ARCH}.rpm
%define _unpackaged_files_terminate_build 0

%description
Home document imaging, with OCR. Scan documents (with SANE) or import ODF documents, assign tags. Use openDIAS to store all our letters, bills, statements, etc in a convenient, safe and easily retrievable way.

%post
systemctl daemon-reload
systemctl enable opendias.service

%preun
systemctl stop opendias.service

%postun
systemctl daemon-reload

%files
%dir "/etc/opendias/"
%config "/etc/opendias/opendias.conf"
%config "/usr/lib/systemd/system/opendias.service"
"/usr/bin/opendias"
"/usr/bin/opendias_worker"
"/usr/bin/opendiasconfig"
%dir "/usr/share/opendias/"
"/usr/share/opendias/openDIAS.sqlite3.dmp.v1.sql"
"/usr/share/opendias/openDIAS.sqlite3.dmp.v2.sql"
"/usr/share/opendias/openDIAS.sqlite3.dmp.v3.sql"
"/usr/share/opendias/openDIAS.sqlite3.dmp.v4.sql"
"/usr/share/opendias/openDIAS.sqlite3.dmp.v5.sql"
"/usr/share/opendias/openDIAS.sqlite3.dmp.v6.sql"
"/usr/share/opendias/openDIAS.sqlite3.dmp.v7.sql"
"/usr/share/opendias/language.resource.en"
"/usr/share/opendias/language.resource.de"
"/usr/share/opendias/language.resource.nl"
%dir "/usr/share/opendias/webcontent/"
"/usr/share/opendias/webcontent/accessControls.html.de"
"/usr/share/opendias/webcontent/accessControls.html.en"
"/usr/share/opendias/webcontent/accessControls.html.nl"
"/usr/share/opendias/webcontent/acquire.html.de"
"/usr/share/opendias/webcontent/acquire.html.en"
"/usr/share/opendias/webcontent/acquire.html.nl"
"/usr/share/opendias/webcontent/body.html.de"
"/usr/share/opendias/webcontent/body.html.en"
"/usr/share/opendias/webcontent/body.html.nl"
"/usr/share/opendias/webcontent/docDetail.html.de"
"/usr/share/opendias/webcontent/docDetail.html.en"
"/usr/share/opendias/webcontent/docDetail.html.nl"
"/usr/share/opendias/webcontent/docList.html.de"
"/usr/share/opendias/webcontent/docList.html.en"
"/usr/share/opendias/webcontent/docList.html.nl"
%dir "/usr/share/opendias/webcontent/images/"
"/usr/share/opendias/webcontent/images/actionrequired.png"
"/usr/share/opendias/webcontent/images/cabinet.jpg"
"/usr/share/opendias/webcontent/images/openDIAS_64x64.ico"
"/usr/share/opendias/webcontent/images/opendias.jpg"
"/usr/share/opendias/webcontent/images/openDIAS_sml.png"
"/usr/share/opendias/webcontent/images/texture.png"
"/usr/share/opendias/webcontent/images/arrow.png"
"/usr/share/opendias/webcontent/images/close.png"
%dir "/usr/share/opendias/webcontent/images/datepicker/"
"/usr/share/opendias/webcontent/images/datepicker/datepicker_bl.png"
"/usr/share/opendias/webcontent/images/datepicker/datepicker_b.png"
"/usr/share/opendias/webcontent/images/datepicker/datepicker_br.png"
"/usr/share/opendias/webcontent/images/datepicker/datepicker_l.png"
"/usr/share/opendias/webcontent/images/datepicker/datepicker_r.png"
"/usr/share/opendias/webcontent/images/datepicker/datepicker_tl.png"
"/usr/share/opendias/webcontent/images/datepicker/datepicker_t.png"
"/usr/share/opendias/webcontent/images/datepicker/datepicker_tr.png"
%dir "/usr/share/opendias/webcontent/images/easySlider/"
"/usr/share/opendias/webcontent/images/easySlider/btn_next.png"
"/usr/share/opendias/webcontent/images/easySlider/btn_prev.png"
%dir "/usr/share/opendias/webcontent/images/jquery-ui/"
"/usr/share/opendias/webcontent/images/jquery-ui/pbar-ani.png"
"/usr/share/opendias/webcontent/images/jquery-ui/ui-bg_diagonals-thick_90_eeeeee_40x40.png"
"/usr/share/opendias/webcontent/images/jquery-ui/ui-bg_flat_15_cd0a0a_40x100.png"
"/usr/share/opendias/webcontent/images/jquery-ui/ui-bg_glass_100_e4f1fb_1x400.png"
"/usr/share/opendias/webcontent/images/jquery-ui/ui-bg_glass_50_3baae3_1x400.png"
"/usr/share/opendias/webcontent/images/jquery-ui/ui-bg_glass_80_d7ebf9_1x400.png"
"/usr/share/opendias/webcontent/images/jquery-ui/ui-bg_highlight-hard_100_f2f5f7_1x100.png"
"/usr/share/opendias/webcontent/images/jquery-ui/ui-bg_highlight-hard_70_000000_1x100.png"
"/usr/share/opendias/webcontent/images/jquery-ui/ui-bg_highlight-soft_100_deedf7_1x100.png"
"/usr/share/opendias/webcontent/images/jquery-ui/ui-bg_highlight-soft_25_ffef8f_1x100.png"
"/usr/share/opendias/webcontent/images/jquery-ui/ui-icons_2694e8_256x240.png"
"/usr/share/opendias/webcontent/images/jquery-ui/ui-icons_2e83ff_256x240.png"
"/usr/share/opendias/webcontent/images/jquery-ui/ui-icons_3d80b3_256x240.png"
"/usr/share/opendias/webcontent/images/jquery-ui/ui-icons_72a7cf_256x240.png"
"/usr/share/opendias/webcontent/images/jquery-ui/ui-icons_ffffff_256x240.png"
%dir "/usr/share/opendias/webcontent/includes/"
"/usr/share/opendias/webcontent/includes/footer.txt.de"
"/usr/share/opendias/webcontent/includes/footer.txt.en"
"/usr/share/opendias/webcontent/includes/footer.txt.nl"
"/usr/share/opendias/webcontent/includes/header.txt.de"
"/usr/share/opendias/webcontent/includes/header.txt.en"
"/usr/share/opendias/webcontent/includes/header.txt.nl"
"/usr/share/opendias/webcontent/includes/jquery.canvas-loader.js"
"/usr/share/opendias/webcontent/includes/jquery.easySlider.js"
"/usr/share/opendias/webcontent/includes/jquery.gzoom.js"
"/usr/share/opendias/webcontent/includes/jquery.js"
"/usr/share/opendias/webcontent/includes/jquery.mousewheel.js"
"/usr/share/opendias/webcontent/includes/jquery.tagsinput.js"
"/usr/share/opendias/webcontent/includes/jquery-ui.min.js"
"/usr/share/opendias/webcontent/includes/openDias.acquire.js"
"/usr/share/opendias/webcontent/includes/openDias.docList.js"
"/usr/share/opendias/webcontent/includes/openDias.userdetails.js"
"/usr/share/opendias/webcontent/includes/openDias.filter.js"
"/usr/share/opendias/webcontent/includes/openDias.accessControls.js"
"/usr/share/opendias/webcontent/includes/openDias.accessMethods.js"
"/usr/share/opendias/webcontent/includes/openDias.loadDetails.js"
"/usr/share/opendias/webcontent/includes/openDias.saveDetails.js"
"/usr/share/opendias/webcontent/includes/sprintf-0.7-beta1.js"
%dir "/usr/share/opendias/webcontent/includes/local/"
"/usr/share/opendias/webcontent/includes/local/generic.resource.de"
"/usr/share/opendias/webcontent/includes/local/generic.resource.en"
"/usr/share/opendias/webcontent/includes/local/generic.resource.nl"
"/usr/share/opendias/webcontent/includes/local/openDias.acquire.js.resource.de"
"/usr/share/opendias/webcontent/includes/local/openDias.acquire.js.resource.en"
"/usr/share/opendias/webcontent/includes/local/openDias.acquire.js.resource.nl"
"/usr/share/opendias/webcontent/includes/local/openDias.docList.js.resource.de"
"/usr/share/opendias/webcontent/includes/local/openDias.docList.js.resource.en"
"/usr/share/opendias/webcontent/includes/local/openDias.docList.js.resource.nl"
"/usr/share/opendias/webcontent/includes/local/openDias.filter.js.resource.de"
"/usr/share/opendias/webcontent/includes/local/openDias.filter.js.resource.en"
"/usr/share/opendias/webcontent/includes/local/openDias.filter.js.resource.nl"
"/usr/share/opendias/webcontent/includes/local/openDias.accessControls.js.resource.de"
"/usr/share/opendias/webcontent/includes/local/openDias.accessControls.js.resource.en"
"/usr/share/opendias/webcontent/includes/local/openDias.accessControls.js.resource.nl"
"/usr/share/opendias/webcontent/includes/local/openDias.loadDetails.js.resource.de"
"/usr/share/opendias/webcontent/includes/local/openDias.loadDetails.js.resource.en"
"/usr/share/opendias/webcontent/includes/local/openDias.loadDetails.js.resource.nl"
"/usr/share/opendias/webcontent/includes/local/openDias.saveDetails.js.resource.de"
"/usr/share/opendias/webcontent/includes/local/openDias.saveDetails.js.resource.en"
"/usr/share/opendias/webcontent/includes/local/openDias.saveDetails.js.resource.nl"
%dir "/usr/share/opendias/webcontent/style/"
"/usr/share/opendias/webcontent/style/common.css"
"/usr/share/opendias/webcontent/style/datepicker.css"
"/usr/share/opendias/webcontent/style/jquery.easyslider.css"
"/usr/share/opendias/webcontent/style/jquery.gzoom.css"
"/usr/share/opendias/webcontent/style/jquery.tagsinput.css"
"/usr/share/opendias/webcontent/style/jquery-ui.css"
"/usr/share/opendias/webcontent/style/print.css"
%dir "/usr/share/doc/opendias/"
"/usr/share/doc/opendias/changelog.gz"
"/usr/share/doc/opendias/copyright"
%dir "/var/lib/opendias/"
%dir "/var/log/opendias/"
